import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import { useRouter } from 'next/router';
import Header from '../components/Navbar';
import Footer from '../components/Footer';

const Home: NextPage = () => {
  const [name, setName] = useState<string>('');
  const router = useRouter();

  const letsGo = () => {
    if (name.length < 3) return alert('Name too small');

    router.push({
      pathname: '/chat',
      query: {
        name
      }
    });
  };

  return (
    <>
      <Header />
      <main className={styles.main}>
        <Head>
          <title>KAJU | HOME</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <title>Home</title>
        </Head>
        <section className={styles.form}>
          <div className={styles.form_div} >
            <div className={styles.person_svg} >
              <i className="bi bi-person"></i>
            </div>
            <input type="text" value={name} onChange={e => setName(e.target.value)} className={styles.inputText} placeholder="What's your name.?" autoComplete='off' required={true} minLength={3} maxLength={10} />
          </div>
          <button type="submit" className={styles.submitBtn} onClick={letsGo}>SUBMIT</button>
        </section>
      </main>
      <Footer />
    </>
  );
};

export default Home;