import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const [name, setName] = useState<string>('');
  const router = useRouter();

  const letsGo = () => {
    console.log(name);

    if (name.length < 3) return alert('Name Too Small.');

    router.push({
      pathname: '/chat',
      query: {
        name
      }
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>KAJU | HOME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <title>Home</title>
      <main className={styles.main}>
        <input type="text" value={name} onChange={e => setName(e.target.value)} className={styles.inputText} placeholder="What's your name.?" autoComplete='off' />
        <button type="submit" className={styles.submitBtn} onClick={letsGo}>SUBMIT</button>
      </main>
    </div>
  )
}

export default Home;