import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const randomNo = async () => {
    fetch('')
      .then(t => t.json())
      .then(res => {
        console.log(res);
      })

    console.log(process.env.API_ENDPOINT);

  };

  return (
    <div className={styles.container}>
      <Head>
        <title>KAJU | HOME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 onClick={randomNo}>btn</h1><br />
        <h1 id="random_no">Random no is: </h1>
      </main>
    </div>
  )
}

export default Home
